### PR TITLE
[Waiting #2] Dockerize the API service including background tasks

### PR DESCRIPTION
**Pull request by knaperek**
Usage: docker-compose up

### CODE REVIEW

**Review by oxarbitrage — COMMENTED** [review]
thanks for adding this, really appreciate it. i dont know much docker but it seems first i need to approve https://github.com/oxarbitrage/bitshares-python-api-backend/pull/2 and change the readme to start the service. 

i'll take a look into the 2 tomorrow and let you know.

**Comment by knaperek** [comment]
Yep you're right, #2 is needed first. I split it into 2 separate PRs because #2 is independent and useful with any deployment technology, not just Docker.

I thought I'd add a complete setup for Docker in order to make it easier for anybody to run the whole app themselves and make contribution easier. You don't have to edit README just yet, I can document the whole thing subsequently. There are some potential bugs in the app that may have been uncovered when I tested the project from fresh start so I'll follow up with further PRs soon. Having it dockerized will help with reproducibility, that's my primary goal right now. When it's all working nicely I'll probably further improve/extend the Docker support and document it properly.

For now, you only need to install Docker and Docker Compose to your computer, and then run `docker compose up` and after a few seconds you are ready to open your browser at http://localhost:5000 (initial launch will take a bit longer).
You can install Docker CE (Comunity Edition) from the official website (you'll find the proper instroctions for your platform). For Docker Compose, my preferred way to install it is via PIP (pip install docker-compose), but you'll find other options in the official docs also if you want.

**Comment by oxarbitrage** [comment]
one of the things that i am using to start the service and that is not documented is that i am running it behind nginx because in a production environment running flask will stop working when several clients connect to it at the same time, it needs a real webserver handling the traffic.

**Comment by knaperek** [comment]
Sure, I was thinking about adding nginx to the docker-compose setup also, but for simplicity I desided to use just uwsgi in the http mode (which is a production ready webserver). If needed I can either extend this compose file or create a new one that includes nginx also. For the first iteration I want to KISS.

**Pull request merged**
