### PR TITLE
Add api to convert operation_types (#50)

### PR DESCRIPTION
**Pull request by Zapata**
- `/operation_type` returns an operation type description by id or name
 - ` /operation_types` return the description of all the operation types
 - description of an operation type is id, name, virtual true/false.

### CODE REVIEW

**Comment by Zapata** [comment]
Related to #50

**Review by oxarbitrage — CHANGES_REQUESTED** [review]
Call fails when `http://localhost:5000/operation_type?id=0` with:

op_type

Also, default is `-1` while it should be `0`.

**Comment by Zapata** [comment]
Should be better now. Some issues with handling 0 value and the default.
It's impossible to set 0 as the default, I have put null to avoid the `-1` trick.

**Review by oxarbitrage — APPROVED** [review]
looks good now, thanks.

**Pull request merged**
